apiVersion: v1
kind: ConfigMap
metadata:
  name: crucible-config
  namespace: lakekeeper
data:
  config.yaml: |
    trino_dsn: "http://admin@localhost:9080?catalog=default&schema=test"
    catalog: "lakekeeper"
    workers: 25
