apiVersion: v1
kind: ConfigMap
metadata:
  name: crucible-config
  namespace: lakehouse
data:
  config.yaml: |
    trino_dsn: "http://admin@trino:8080?catalog=default&schema=test"
    catalog: "lakekeeper"
    workers: 3
