apiVersion: batch/v1
kind: Job
metadata:
  name: crucible-job
spec:
  template:
    spec:
      containers:
      - name: crucible
        image: crucible:latest
        imagePullPolicy: Never
        volumeMounts:
        - name: config
          mountPath: /app/config.yaml
          subPath: config.yaml
      restartPolicy: Never
      volumes:
      - name: config
        configMap:
          name: crucible-config
  backoffLimit: 2
